Fix a overloaded max is ambiguous.
The code

    typedef mpfr::mpreal real;
    using std::max;
    real a = 1, b = 2;
    real c = max(a,b);

gives

  error: call of overloaded ‘max(real&, real&)’ is ambiguous

There are 3 candidates are

../mpreal.h:3125:32: note: candidate: ‘const mpfr::mpreal& std::max(const mpfr::mpreal&, const mpfr::mpreal&, bool)’
/usr/include/c++/9/bits/stl_algobase.h:222:5: note: candidate: ‘constexpr const _Tp& std::max(const _Tp&, const _Tp&) [with _Tp = mpfr::mpreal]’
../mpreal.h:2660:22: note: candidate: ‘const mpfr::mpreal
mpfr::max(const mpfr::mpreal&, const mpfr::mpreal&)’

making the "omitnan" args to the name std::max/min required fixes the
problem.

(I need the "using std::max", so that when real is a double, std::max
gets invoked.)